### ISSUE TITLE
Is a map needed for using  this package

### ISSUE THREAD

**Issue by ghost** [rst-tu-dortmund/teb_local_planner-release#1]
Hi all,

I am about to start a project using Teb_local_planner and need to make sure about a few things before starting. As I understood, this package does not require a known-map previously, so lets say if configured well, I can use a robot to navigate and make it to a goal and avoid obstacles.
Is that correct?

P.s in tutorials, I could not get the package running without a map, (maybe im doing something wrong) which made me want to ask just to be on the safe side when using this package.

Kind regards,

**Comment by croesmann** [comment]
Hi @MomoTavas,

the teb_local_planner is a plugin for move_base (ROS navigation stack),
hence you need to configure move_base in order to work without a map.
E.g. create a local and global costmap with an "empty world" and just include the ObstacleLayer.
Generally, from the teb_local_planner point of view, you could completely deactivate the inclusion of the costmap (there is a parameter), but provide obstacles via a separate topic.
Nevertheless, move_base has to be configured appropriately: You can find several questions and answers
at [answers.ros.org](answers.ros.org).

Cheers,
Christoph

PS: this is the release-repo, used for ROS packaging. You probably want to refer to https://github.com/rst-tu-dortmund/teb_local_planner.git

**Comment by ghost** [comment]
Hi Christoph,

Many thanks to your quick reply and guides. Then, I believe that’s what I am looking for however I am new to costmap but it should not be a big deal to sort things out.

Thanks again.

Kind regards,


________________________________
